service: rrs-serverless

provider:
  name: aws
  stage: dev
  region: ap-south-1
  memorySize: 512

functions:
  nextJsApp:
    handler: serverless/index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: GET

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true